apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/argocd/app-db"
type: Opaque
stringData:
  DB_USER: <username>
  DB_PASS: <password>
